language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
os:
  - linux

# command to install dependencies
install:
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  - pip install electrumsv-secp256k1
  - pip install pycodestyle
  - pip install pyaes
  - pip install pylint

# command to run tests
script:
  - pytest --cov=bitcoinx
#  - pylint --disable=C0103,C0111,R0201,W1203,R0205,R0902,C0235,R1705,R0903,R0913,C0325,W0212 bitcoinx/[^_]*.py
  - pycodestyle --max-line-length=100 bitcoinx/*.py

after_success: coveralls
