language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
os:
  - linux
#  - windows
#  - osx
# command to install dependencies
install:
  - pip install -e .
#  - pip install pytest-asyncio
  - pip install pytest-cov
  - pip install coveralls
  - pip install electrumsv-secp256k1
  - pip install pycodestyle
#  - pip install Sphinx
# command to run tests
script:
  - pytest --cov=bitcoinx
  - pycodestyle --max-line-length=100 bitcoinx/*.py
#  - sh -c "cd docs && make html"
after_success: coveralls
