pr:
  - master
  - releases/*

jobs:
- template: run-tests.yml
  parameters:
    name: Py37_Ubuntu
    vmImage: 'ubuntu-16.04'
    pythonVersion: '3.7'
- template: run-tests.yml
  parameters:
    name: Py37_Mac
    vmImage: 'macOS-10.14'
    pythonVersion: '3.7'
- template: run-tests.yml
  parameters:
    name: Py37_Win
    vmImage: 'windows-2019'
    pythonVersion: '3.7'
- template: run-tests.yml
  parameters:
    name: Py38_Ubuntu
    vmImage: 'ubuntu-16.04'
    pythonVersion: '3.8'
- template: run-tests.yml
  parameters:
    name: Py38_Mac
    vmImage: 'macOS-10.14'
    pythonVersion: '3.8'
- template: run-tests.yml
  parameters:
    name: Py38_Win
    vmImage: 'windows-2019'
    pythonVersion: '3.8'
- template: run-tests.yml
  parameters:
    name: Py39_Ubuntu
    vmImage: 'ubuntu-16.04'
    pythonVersion: '3.9'
- template: run-tests.yml
  parameters:
    name: Py39_Mac
    vmImage: 'macOS-10.14'
    pythonVersion: '3.9'
- template: run-tests.yml
  parameters:
    name: Py39_Win
    vmImage: 'windows-2019'
    pythonVersion: '3.9'
