pr:
  - master
  - releases/*

jobs:
- template: run-tests.yml
  parameters:
    name: TestPython37_Ubuntu
    vmImage: 'ubuntu-16.04'
    pythonVersion: '3.7'
- template: run-tests.yml
  parameters:
    name: TestPython37_Mac
    vmImage: 'macOS-10.14'
    pythonVersion: '3.7'
- template: run-tests.yml
  parameters:
    name: TestPython37_Win
    vmImage: 'windows-2019'
    pythonVersion: '3.7'
- template: run-tests.yml
  parameters:
    name: TestPython37_Ubuntu
    vmImage: 'ubuntu-16.04'
    pythonVersion: '3.8'
- template: run-tests.yml
  parameters:
    name: TestPython37_Mac
    vmImage: 'macOS-10.14'
    pythonVersion: '3.8'
- template: run-tests.yml
  parameters:
    name: TestPython37_Win
    vmImage: 'windows-2019'
    pythonVersion: '3.8'
- template: run-tests.yml
  parameters:
    name: TestPython37_Ubuntu
    vmImage: 'ubuntu-16.04'
    pythonVersion: '3.9'
- template: run-tests.yml
  parameters:
    name: TestPython37_Mac
    vmImage: 'macOS-10.14'
    pythonVersion: '3.9'
- template: run-tests.yml
  parameters:
    name: TestPython37_Win
    vmImage: 'windows-2019'
    pythonVersion: '3.9'
