parameters:
  onlyPullRequests: false

steps:
- script: |
    python3 -m pip install electrumsv-secp256k1 pyaes
    python3 -m pip install pycodestyle
    python3 -m pip install coveralls coverage
    python3 -m pip install pytest
  displayName: Prepare general environment
  condition: |
    and(
      succeeded(),
      or(
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(${{ parameters.onlyPullRequests }}, false)
      )
    )
  enabled: true
  continueOnError: false
  failOnStderr: false